### ISSUE TITLE
Large Uploads wont't resume 

### ISSUE THREAD

**Issue by tcaraccia** [cloudinary/cloudinary_java#169]
Every time the application is removed from the "Recent Activities" list or when Android closes it due to low memory uploads starts from zero.
Android SDK: 28 
Cloudinary SDK: 1.26.0 
Android versions tested: 7.1, 8.0 and 9. I also suspect it happens on 5 and 6.

Expected Behaviour:
It should resume remaining bytes to finish upload.

**Comment by leptians** [comment]
Hi Tomas,

Thank you for reaching out to us on this.

Unfortunately if the application is closed or killed when Android closes it due to low memory, upload needs to be restarted.
However if the upload is in the background, then the background handler will automatically resume/continue the upload chunk by chunk.

If you believe if this is the scenario, I suggest to share us the detail information of the upload such as timestamp, timezone, and public id it's being uploaded in a ticket.

Hope this helps.

Regards,
Erwin Lukas
