### ISSUE TITLE
How can I cancel an ongoing upload in your Android SDK?

### ISSUE THREAD

**Issue by anad7** [cloudinary/cloudinary_java#36]
I am not able to identify the way to cancel ongoing uploads, this is a very common use case where the ongoing request should be cancelled when the user navigates away from upload Activity or Fragment.

**Comment by beeeku** [comment]
+1

**Comment by roeeba** [comment]
Hi @anad7 . We apologize for the very delayed response. While it's probably not relevant anymore, the `MediaManager.cancel` method is what you're looking for (Supported for Android, not Java). We're going to close this issue because of the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket, if our assistance is still needed.
